name: Test Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: npm run type-check

    - name: Test build process
      run: npm run build:exe

    - name: Verify build artifacts
      run: |
        echo "Checking build artifacts..."
        ls -la build/
        echo "Verifying executable files exist..."
        test -f build/resume-generator-win.exe || (echo "Windows executable not found!" && exit 1)
        test -f build/resume-generator-macos || (echo "macOS executable not found!" && exit 1)
        test -f build/resume-generator-linux || (echo "Linux executable not found!" && exit 1)
        echo "✅ All executables built successfully!"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test-build-${{ github.sha }}
        path: |
          build/resume-generator-win.exe
          build/resume-generator-macos
          build/resume-generator-linux
        retention-days: 7
